project:
  environment: "local" #local or docker

mongodb:
  environment: "local" #where are you connecting to the mongo
  username: "root"
  password: "psw"
  local:
    address: "127.0.0.1"
    port: 27017
  docker:
    address: "mongo"
    port: 27017
  atlas:
    connection_string: "mongodb+srv://admin:psw@cluster0.ew7zhpy.mongodb.net/"
  databases:
    api_raw: "api_raw"
    preprocess_data: "preprocess_data"
    output: "output"

kafka:
  local:
    zookeeper-1:
      address: "127.0.0.1"
      port: 2181
    broker-1:
      address: "127.0.0.1"
      port: 29092
    broker-2:
      address: "127.0.0.1"
      port: 39092
    broker-3:
      address: "127.0.0.1"
      port: 49092
  docker:
    zookeeper-1:
      address: "zookeeper"
      port: 2181
    broker-1:
      address: "kafka-1"
      port: 9092
    broker-2:
      address: "kafka-2"
      port: 9092
    broker-3:
      address: "kafka-3"
      port: 9092
  topics:
    input-head: "input"
    head-api_sink: "starter"
    api_sink-tail: "data_status"
    tail-output: "output"
    