project:
  environment: "docker" #local or docker

mongodb:
  environment: "atlas" #where is the mongodb server
  local:
    address: "127.0.0.1"
    port: 27017
  docker:
    address: "mongo1"
    port: 27017
  atlas:
    connection_string: "mongodb+srv://admin:psw@cluster0.ew7zhpy.mongodb.net/"

kafka:
  local:
    zookeeper-1:
      address: "127.0.0.1"
      port: 2181
    broker-1:
      address: "127.0.0.1"
      port: 29092
    broker-2:
      address: "127.0.0.1"
      port: 39092
  docker:
    zookeeper-1:
      address: "zookeeper"
      port: 2181
    broker-1:
      address: "kafka-1"
      port: 9092
    broker-2:
      address: "kafka-2"
      port: 9092
  topics:
    head-api_sink: "starter"
    api_sink-head: "data_status"
    